export const STORAGE_KEYS = {
  LEGACY_SHIFTS: "hgv-shifts", // preserved forever, read-only after migration
  SCHEMA_VERSION: "wt-schema-version",
  CURRENT_PERSON_ID: "wt-current-person-id",
  WORKSPACES: "wt-workspaces",
  PEOPLE: "wt-people",
  MEMBERSHIPS: "wt-memberships",
  ORGANISATIONS: "wt-organisations",
  SITES: "wt-sites",
  DRIVER_PROFILES: "wt-driver-profiles",
  ENGAGEMENTS: "wt-engagements",
  ASSIGNMENTS: "wt-assignments",
  SHIFTS: "wt-shifts",
  RATE_CARDS: "wt-rate-cards",
  RATE_CARD_LINEAGES: "wt-rate-card-lineages",
  PLACEMENTS: "wt-placements",
  COMPLIANCE_PROFILES: "wt-compliance-profiles",
  VEHICLES: "wt-vehicles",
  CHECKLIST_TEMPLATES: "wt-checklist-templates",
  VEHICLE_CHECKS: "wt-vehicle-checks",
  DEFECTS: "wt-defects",
  LOADS: "wt-loads",
  DRIVER_DOCUMENTS: "wt-driver-documents",
  CPC_TRAINING_RECORDS: "wt-cpc-training-records",
};
